Repository rdohms/dms-filter-bundle, pull requests merged in 2021-07, with the labels that each got.

#209 Allow Symfony 5
  .github/workflows/run-tests.yml
  .gitignore
  composer.json
  composer.lock
  src/DMS/Bundle/FilterBundle/DependencyInjection/Configuration.php
  src/DMS/Bundle/FilterBundle/Form/Type/FormTypeFilterExtension.php
  src/DMS/Bundle/FilterBundle/Tests/AnnotationLoadingTest.php
  src/DMS/Bundle/FilterBundle/Tests/Form/EventListener/DelegatingFilterListenerTest.php
  src/DMS/Bundle/FilterBundle/Tests/Form/Type/FormTypeFilterExtensionTest.php
  src/DMS/Bundle/FilterBundle/Tests/Integration/ContainerTest.php
  src/DMS/Bundle/FilterBundle/Tests/Loader/ContainerAwareLoaderTest.php
Labels: dependencies, refactoring

#221 Update lockfile to match newest versions
  composer.lock
Labels: Dependencies

#222 Applied dms/coding-standard codestyle
  .github/workflows/check-cs.yml
  .github/workflows/run-tests.yml
  README.md
  composer.json
  composer.lock
  phpcs.xml.dist
  src/DMS/Bundle/FilterBundle/DMSFilterBundle.php
  src/DMS/Bundle/FilterBundle/DependencyInjection/Configuration.php
  src/DMS/Bundle/FilterBundle/DependencyInjection/DMSFilterExtension.php
  src/DMS/Bundle/FilterBundle/Filter/ContainerFilter.php
  src/DMS/Bundle/FilterBundle/Form/EventListener/DelegatingFilterListener.php
  src/DMS/Bundle/FilterBundle/Form/FilterExtension.php
  src/DMS/Bundle/FilterBundle/Form/Type/FormTypeFilterExtension.php
  src/DMS/Bundle/FilterBundle/Loader/ContainerAwareLoader.php
  src/DMS/Bundle/FilterBundle/Rule/Service.php
  src/DMS/Bundle/FilterBundle/Service/Filter.php
  src/DMS/Bundle/FilterBundle/Tests/AnnotationLoadingTest.php
  src/DMS/Bundle/FilterBundle/Tests/Dummy/AnnotatedClass.php
  src/DMS/Bundle/FilterBundle/Tests/Form/EventListener/DelegatingFilterListenerTest.php
  src/DMS/Bundle/FilterBundle/Tests/Form/Type/FormTypeFilterExtensionTest.php
  src/DMS/Bundle/FilterBundle/Tests/Integration/ContainerTest.php
  src/DMS/Bundle/FilterBundle/Tests/Loader/ContainerAwareLoaderTest.php
Labels: CI, Dependencies, Documentation

#44 Update Service Rule to accept custom options
  src/DMS/Bundle/FilterBundle/Filter/ContainerFilter.php
  src/DMS/Bundle/FilterBundle/Rule/Service.php
Labels: feature

#229 Allow v4 of DMS filter
  composer.json
  composer.lock
  src/DMS/Bundle/FilterBundle/Loader/ContainerAwareLoader.php
  src/DMS/Bundle/FilterBundle/Tests/Loader/ContainerAwareLoaderTest.php
Labels: Dependencies
